### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by winniehell**
It seems like it works for newer versions of angular as well...

### CODE REVIEW

**Comment by winniehell** [comment]
See also http://winniehell-forks.github.io/angular-ui-router-anim-in-out/

**Comment by homerjam** [comment]
Cool, thanks. How will this effect projects using 1.2 or 1.3? Might it be safer to have >=1.2?

**Comment by winniehell** [comment]
Sure, `>=1.2` would be an option. If that is what you'd prefer, I'll change it.

**Comment by homerjam** [comment]
I think that may cause less hassle for those stuck with 1.2 or 1.3. If you wouldn't mind changing that'd be great.

**Comment by winniehell** [comment]
Sorry, I forgot about that. Version numbers are now backwards compatible.

**Comment by homerjam** [comment]
Great, thanks

**Pull request merged**
